spring:
  application:
    name: auth-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    oauth:
      path: /auth-auth/**
      serviceId: auth-auth
      strip-prefix: false
      custom-sensitive-headers: true                                    # zuul授权码跳转
    user:
      path: /auth-user/**
      serviceId: auth-user
      strip-prefix: false